In [1]:
from pathlib import Path
import pandas as pd
import numpy as np
import cv2
import matplotlib.pyplot as plt
import easyocr

ラウンド中かどうかの仮判定から決めたラウンド数と実際にUIのOCRでラウンド数を比べて妥当性を検証

In [3]:
vod_title = "M8 vs. EDG - VALORANT Masters Santiago - SWISS"
video_path = Path(f"../../data/vods/{vod_title}.mp4")
labels_path = Path(f"../../data/processed/round_labels/{vod_title}_round_labels.csv")
checked_path = Path(f"../../data/processed/round_labels/{vod_title}_round_labels_checked.csv")
checked_pd = pd.read_csv(checked_path)
df = pd.read_csv(labels_path)
reader = easyocr.Reader(["en"],gpu=False)

Using CPU. Note: This module is much faster with a GPU.

In [4]:
def read_frame_at_sec(video_path, t_sec):
    cap = cv2.VideoCapture(str(video_path))
    if not cap.isOpened():
        raise ValueError(f"Cannot open video: {video_path}")

    fps = cap.get(cv2.CAP_PROP_FPS)
    frame_idx = int(t_sec * fps)
    cap.set(cv2.CAP_PROP_POS_FRAMES, frame_idx)

    ret, frame = cap.read()
    cap.release()

    if not ret:
        raise ValueError(f"Failed to read frame at {t_sec} sec")

    return frame

def crop_round_region(frame):
    h, w = frame.shape[:2]

    x1 = int(w * 0.51)
    x2 = int(w * 0.527)
    y1 = int(h * 0.01)
    y2 = int(h * 0.025)

    return frame[y1:y2, x1:x2]

def preprocess_round_number_for_ocr(img, scale=3):
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

    gray = cv2.resize(
        gray,
        None,
        fx=scale,
        fy=scale,
        interpolation=cv2.INTER_CUBIC
    )

    gray = cv2.GaussianBlur(gray, (3, 3), 0)

    _, th_fixed = cv2.threshold(gray, 180, 255, cv2.THRESH_BINARY)

    _, th_otsu = cv2.threshold(
        gray, 0, 255,
        cv2.THRESH_BINARY + cv2.THRESH_OTSU
    )

    th_adaptive = cv2.adaptiveThreshold(
        gray, 255,
        cv2.ADAPTIVE_THRESH_GAUSSIAN_C,
        cv2.THRESH_BINARY,
        11, 2
    )

    return {
        "gray": gray,
        "fixed": th_fixed,
        "otsu": th_otsu,
        "adaptive": th_adaptive,
    }

def read_round_number_from_crop(crop, reader):
    processed_imgs = preprocess_round_number_for_ocr(crop)

    for name, img in processed_imgs.items():
        results = reader.readtext(
            img,
            detail=0,
            allowlist="0123456789"
        )

        if len(results) == 0:
            continue

        text = "".join(results).strip()

        if text.isdigit():
            n = int(text)
            if 1 <= n <= 45:
                return n

    return None

def read_round_number_at_sec(video_path, t_sec, reader):
    frame = read_frame_at_sec(video_path, t_sec)
    crop = crop_round_region(frame)
    return read_round_number_from_crop(crop, reader)

def read_round_numbers_near_time(video_path, t_sec, reader, offsets=(-3, 0, 3)):
    results = []

    for offset in offsets:
        t = t_sec + offset

        try:
            round_no = read_round_number_at_sec(video_path, t, reader)
        except Exception as e:
            round_no = None

        results.append({
            "t_sec": t,
            "offset": offset,
            "round_no": round_no,
        })

    return results

In [5]:
with pd.option_context("display.max_rows", None, "display.max_columns", None):
    display(df)

,value,start_sec,end_sec,n_samples,mean_diff,min_diff,max_diff,duration_sec,t_sec,t_min,left_score,right_score,left_score_candidates,right_score_candidates,score_total,round_no_from_score,map_no,round_no,left_win_label
0,True,9.009,78.078,70,22.858459,17.960205,26.488715,70.070,9.009,0.150150,0,0,"[0, 0, 0]","[0, 0, 0]",0,1,1,1,1.0
1,True,106.106,203.203,98,23.621082,19.780490,27.049723,98.098,106.106,1.768433,1,0,"[1, 1, 1]","[0, 0, 0]",1,2,1,2,0.0
2,True,235.235,278.278,44,25.698283,21.291341,27.700168,44.044,235.235,3.920583,1,1,"[1, 1, 1]","[1, 1, 1]",2,3,1,3,0.0
3,True,297.297,390.390,94,25.161743,19.347548,27.986844,94.094,297.297,4.954950,1,2,"[1, 1, 1]","[2, 2, 2]",3,4,1,4,1.0
4,True,421.421,515.515,95,23.683746,19.510579,27.125407,95.095,421.421,7.023683,2,2,"[2, 2, 2]","[2, 2, 2]",4,5,1,5,0.0
5,True,542.542,650.650,109,23.825269,19.197130,27.194607,109.109,542.542,9.042367,2,3,"[2, 2, 2]","[3, 3, 3]",5,6,1,6,0.0
6,True,736.736,862.862,127,24.199966,18.810683,27.099338,127.127,736.736,12.278933,2,4,"[2, 2, 2]","[4, 4, 4]",6,7,1,7,0.0
7,True,895.895,972.972,78,25.151095,18.837484,26.630968,78.078,895.895,14.931583,2,5,"[2, 2, 2]","[5, 5, 5]",7,8,1,8,0.0
8,True,991.991,1148.147,157,23.723775,18.561252,27.512126,157.157,991.991,16.533183,2,6,"[2, 2, 2]","[6, 6, 6]",8,9,1,9,0.0
9,True,1170.169,1262.261,93,21.988577,18.152751,26.461480,93.093,1170.169,19.502817,2,7,"[2, 2, 2]","[7, 7, 7]",9,10,1,10,1.0
10,True,1301.300,1382.381,82,22.366953,18.454508,25.489990,82.082,1301.300,21.688333,3,7,"[3, 3, 3]","[7, 7, 7]",10,11,1,11,1.0
11,True,1421.420,1474.473,54,24.010652,17.926649,25.997179,54.054,1421.420,23.690333,4,7,"[4, 4, 4]","[7, 7, 7]",11,12,1,12,0.0
12,True,1617.616,1688.687,72,18.887600,13.990343,21.627143,72.072,1617.616,26.960267,4,8,"[4, 4, 4]","[8, 8, 8]",12,13,1,13,0.0
13,True,1714.713,1793.792,80,17.993038,11.686578,21.487576,80.080,1714.713,28.578550,4,9,"[4, 4, 4]","[9, 9, 9]",13,14,1,14,0.0
14,True,1814.813,1919.918,106,14.546125,9.996474,17.822971,106.106,1814.813,30.246883,4,10,"[4, 4, 4]","[10, 10, 10]",14,15,1,15,1.0
15,True,1949.948,2067.065,118,15.365243,10.844835,18.269233,118.118,1949.948,32.499133,5,10,"[5, 5, 5]","[10, 10, 10]",15,16,1,16,1.0
16,True,2153.151,2225.223,73,15.355140,9.336426,18.829074,73.073,2153.151,35.885850,6,10,"[6, 6, 6]","[10, 10, 10]",16,17,1,17,1.0
17,True,2244.242,2338.336,95,15.164330,10.035211,18.863905,95.095,2244.242,37.404033,7,10,"[7, 7, 7]","[10, 10, 10]",17,18,1,18,1.0
18,True,2368.366,2420.418,53,14.907016,9.344672,17.749295,53.053,2368.366,39.472767,8,10,"[8, 8, 8]","[10, 10, 10]",18,19,1,19,1.0
19,True,2451.449,2574.572,124,14.993425,5.611410,18.347873,124.124,2451.449,40.857483,9,10,"[9, 9, 9]","[10, 10, 10]",19,20,1,20,1.0
20,True,2665.663,2771.769,107,8.740486,4.437717,15.958550,107.107,2665.663,44.427717,10,10,"[10, 10, 10]","[10, 10, 10]",20,21,1,21,0.0
21,True,2795.793,2885.883,91,10.842537,5.859809,14.472168,91.091,2795.793,46.596550,10,11,"[10, 10, 10]","[11, 11, 11]",21,22,1,22,0.0
22,True,2985.983,3099.096,114,8.940411,0.000000,13.375597,114.114,2985.983,49.766383,10,12,"[10, 10, 10]","[12, 12, 12]",22,23,1,23,1.0
23,True,3125.122,3229.226,105,10.462846,6.556424,14.429742,105.105,3125.122,52.085367,11,12,"[11, 11, 11]","[12, 12, 12]",23,24,1,24,NaN
24,True,3242.239,3284.281,43,22.978553,18.324354,24.937337,43.043,3242.239,54.037317,0,0,"[0, 0, 0]","[0, 0, 0]",0,1,2,1,1.0
25,True,3313.310,3372.369,60,23.372730,18.725016,26.152425,60.060,3313.310,55.221833,1,0,"[1, 1, 1]","[0, 0, 0]",1,2,2,2,1.0
26,True,3398.395,3486.483,89,23.503907,19.120904,26.315728,89.089,3398.395,56.639917,2,0,"[2, 2, 2]","[0, 0, 0]",2,3,2,3,0.0
27,True,3507.504,3564.561,58,25.188809,18.771539,27.473606,58.058,3507.504,58.458400,2,1,"[2, 2, 2]","[1, 1, 1]",3,4,2,4,0.0
28,True,3593.590,3704.701,112,23.446161,18.530002,26.867052,112.112,3593.590,59.893167,2,2,"[2, 2, 2]","[2, 2, 2]",4,5,2,5,1.0
29,True,3732.729,3801.798,70,23.863802,18.407444,26.390978,70.070,3732.729,62.212150,3,2,"[3, 3, 3]","[2, 2, 2]",5,6,2,6,0.0
30,True,3832.829,3940.937,109,22.810702,18.564914,26.491157,109.109,3832.829,63.880483,3,3,"[3, 3, 3]","[3, 3, 3]",6,7,2,7,1.0
31,True,3970.967,4025.021,55,25.429773,22.122803,26.820150,55.055,3970.967,66.182783,4,3,"[4, 4, 4]","[3, 3, 3]",7,8,2,8,1.0
32,True,4055.051,4269.265,215,23.135734,18.097114,26.537435,215.215,4055.051,67.584183,5,3,"[5, 5, 5]","[3, 3, 3]",8,9,2,9,NaN
33,True,4358.354,4489.485,132,23.180901,17.496799,26.116753,132.132,4358.354,72.639233,6,4,"[6, 6, 6]","[4, 4, 4]",10,11,2,10,0.0
34,True,4504.500,4561.557,58,23.370151,17.684543,25.726264,58.058,4504.500,75.075000,6,5,"[6, 6, 6]","[5, 5, 5]",11,12,2,11,0.0
35,True,4707.703,4846.842,140,18.290755,13.263672,24.383599,140.140,4707.703,78.461717,6,6,"[6, 6, 6]","[None, 6, 6]",12,13,2,12,1.0
36,True,4879.875,4982.978,104,19.131508,14.604628,21.955322,104.104,4879.875,81.331250,7,6,"[7, 7, 7]","[6, 6, 6]",13,14,2,13,0.0
37,True,5022.017,5135.130,114,18.513291,13.944010,22.254150,114.114,5022.017,83.700283,7,7,"[7, 7, 7]","[7, 7, 7]",14,15,2,14,0.0
38,True,5150.145,5252.247,103,18.012072,13.363254,21.365506,103.103,5150.145,85.835750,7,8,"[7, 7, 7]","[8, 8, 8]",15,16,2,15,0.0
39,True,5344.339,5435.430,92,18.075620,9.574761,24.011013,92.092,5344.339,89.072317,7,9,"[7, 7, 7]","[9, 9, 9]",16,17,2,16,0.0
40,True,5469.464,5574.569,106,14.659329,10.677382,17.938368,106.106,5469.464,91.157733,7,10,"[7, 7, 7]","[10, 10, 10]",17,18,2,17,0.0
41,True,5596.591,5607.602,12,17.320532,17.198649,17.744765,12.012,5596.591,93.276517,7,11,"[7, 7, 7]","[11, 11, 11]",18,19,2,18,NaN
42,True,5679.674,5764.759,86,14.349154,9.363173,17.445123,86.086,5679.674,94.661233,7,11,"[7, 7, 7]","[11, 11, 11]",18,19,2,19,0.0
43,True,5796.791,5897.892,102,13.513559,9.481961,17.052979,102.102,5796.791,96.613183,7,12,"[7, 7, 7]","[12, 12, 12]",19,20,2,20,NaN

In [ ]:
start_offsets = [1,2,3,5]
end_offsets = [-5,-3,-2,-1]
df["round_ocr_start_samples"] = df["start_sec"].apply(
    lambda t: read_round_numbers_near_time(video_path, t, reader,offsets=start_offsets)
)
df["round_ocr_end_samples"] = df["end_sec"].apply(
    lambda t: read_round_numbers_near_time(video_path, t, reader,offsets=end_offsets)
)

c:\Users\ryo16\Desktop\valorant-\.venv\Lib\site-packages\torch\utils\data\dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

In [14]:
from collections import Counter

def majority_round(samples):
    values = [s["round_no"] for s in samples if s["round_no"] is not None]
    if not values:
        return None
    return Counter(values).most_common(1)[0][0]

df["round_ocr_start"] = df["round_ocr_start_samples"].apply(majority_round)
df["round_ocr_end"] = df["round_ocr_end_samples"].apply(majority_round)
df["round_check_start"] = df["round_ocr_start"] == df["round_no"]
df["round_check_end"] = df["round_ocr_end"] == df["round_no"]
bad_end = df[df["round_check_end"] == False]
bad_start = df[df["round_check_end"] == False]

In [21]:
with pd.option_context("display.max_rows", None, "display.max_columns", None):
    display(df[["map_no","start_sec","end_sec", "round_no","round_ocr_start", "round_ocr_end"]])

    map_no  start_sec   end_sec  round_no  round_ocr_start  round_ocr_end
0        1      9.009    78.078         1                1              1
1        1    106.106   203.203         2                2              2
2        1    235.235   278.278         3                3              3
3        1    297.297   390.390         4                4              4
4        1    421.421   515.515         5                5              5
5        1    542.542   650.650         6                6              6
6        1    736.736   862.862         7                7              7
7        1    895.895   972.972         8                8              8
8        1    991.991  1148.147         9                9              9
9        1   1170.169  1262.261        10               10             10
10       1   1301.300  1382.381        11               11             11
11       1   1421.420  1474.473        12               12             12
12       1   1617.616  1688.687        13               13             13
13       1   1714.713  1793.792        14               14             14
14       1   1814.813  1919.918        15               15             15
15       1   1949.948  2067.065        16               16             16
16       1   2153.151  2225.223        17               17             17
17       1   2244.242  2338.336        18               18             18
18       1   2368.366  2420.418        19               19             19
19       1   2451.449  2574.572        20               20             20
20       1   2665.663  2771.769        21               21             21
21       1   2795.793  2885.883        22               22             22
22       1   2985.983  3099.096        23               23             23
23       1   3125.122  3229.226        24               24             24
24       2   3242.239  3284.281         1                1              1
25       2   3313.310  3372.369         2                2              2
26       2   3398.395  3486.483         3                3              3
27       2   3507.504  3564.561         4                4              4
28       2   3593.590  3704.701         5                5              5
29       2   3732.729  3801.798         6                6              6
30       2   3832.829  3940.937         7                7              7
31       2   3970.967  4025.021         8                8              8
32       2   4055.051  4269.265         9                9             10
33       2   4358.354  4489.485        10               11             11
34       2   4504.500  4561.557        11               12             12
35       2   4707.703  4846.842        12               13             13
36       2   4879.875  4982.978        13               14             14
37       2   5022.017  5135.130        14               15             16
38       2   5150.145  5252.247        15               16             16
39       2   5344.339  5435.430        16               17             17
40       2   5469.464  5574.569        17               18             18
41       2   5596.591  5607.602        18               19             19
42       2   5679.674  5764.759        19               19             19
43       2   5796.791  5897.892        20               20             20