In [3]:
import sys
!{sys.executable} -m pip install requests beautifulsoup4 pandas lxml

Requirement already satisfied: requests in c:\Users\ryo16\Desktop\dl_practice\.venv\Lib\site-packages (2.32.5)
Requirement already satisfied: beautifulsoup4 in c:\Users\ryo16\Desktop\dl_practice\.venv\Lib\site-packages (4.14.3)
Requirement already satisfied: pandas in c:\Users\ryo16\Desktop\dl_practice\.venv\Lib\site-packages (3.0.1)
Requirement already satisfied: lxml in c:\Users\ryo16\Desktop\dl_practice\.venv\Lib\site-packages (6.0.2)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\Users\ryo16\Desktop\dl_practice\.venv\Lib\site-packages (from requests) (3.4.5)
Requirement already satisfied: idna<4,>=2.5 in c:\Users\ryo16\Desktop\dl_practice\.venv\Lib\site-packages (from requests) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\Users\ryo16\Desktop\dl_practice\.venv\Lib\site-packages (from requests) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\Users\ryo16\Desktop\dl_practice\.venv\Lib\site-packages (from requests) (2026.2.25)
Requirement already satisfied: soupsieve>=1.6.1 in c:\Users\ryo16\Desktop\dl_practice\.venv\Lib\site-packages (from beautifulsoup4) (2.8.3)
Requirement already satisfied: typing-extensions>=4.0.0 in c:\Users\ryo16\Desktop\dl_practice\.venv\Lib\site-packages (from beautifulsoup4) (4.15.0)
Requirement already satisfied: numpy>=2.3.3 in c:\Users\ryo16\Desktop\dl_practice\.venv\Lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\Users\ryo16\Desktop\dl_practice\.venv\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\ryo16\Desktop\dl_practice\.venv\Lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in c:\Users\ryo16\Desktop\dl_practice\.venv\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [4]:
!pip install python-dateutil

Requirement already satisfied: python-dateutil in C:\Users\ryo16\Desktop\dl_practice\.venv\Lib\site-packages (2.9.0.post0)
Requirement already satisfied: six>=1.5 in C:\Users\ryo16\Desktop\dl_practice\.venv\Lib\site-packages (from python-dateutil) (1.17.0)

In [5]:
import re
import time 
import requests
import pandas as pd 
from dateutil import parser as dtparser
from datetime import datetime, timezone

In [6]:

YOUTUBE_API_KEY = "AIzaSyCnOPxHO2FxYyh9KS-uumqfDVjAp8WZ23Y"

TOURNAMENT_NAME = "Masters Santiago"
CHANNEL_HANDLE = "@ValorantEsports"

# 公式サイトの表記に合わせて広めに取る
DATE_FROM = pd.Timestamp("2026-02-28", tz="UTC")
DATE_TO   = pd.Timestamp("2026-03-17", tz="UTC")

In [7]:
def yt_get(endpoint: str, params: dict) -> dict:
    url = f"https://www.googleapis.com/youtube/v3/{endpoint}"
    params = dict(params)
    params["key"] = YOUTUBE_API_KEY
    r = requests.get(url, params=params, timeout=30)
    r.raise_for_status()
    return r.json()

In [8]:
def get_channel_and_uploads_playlist(handle: str):
    data = yt_get(
        "channels",
        {
            "part": "snippet,contentDetails",
            "forHandle": handle,
            "maxResults": 1,
        },
    )
    items = data.get("items", [])
    if not items:
        raise ValueError(f"Channel not found for handle={handle}")
    
    ch = items[0]
    channel_id = ch["id"]
    uploads_playlist_id = ch["contentDetails"]["relatedPlaylists"]["uploads"]
    channel_title = ch["snippet"]["title"]
    return {
        "channel_id": channel_id,
        "channel_title": channel_title,
        "uploads_playlist_id": uploads_playlist_id,
    }

channel_info = get_channel_and_uploads_playlist(CHANNEL_HANDLE)
channel_info

{'channel_id': 'UCA1d3HFGFUmkKr2JIUA5Vlw',
 'channel_title': 'VALORANT Champions Tour',
 'uploads_playlist_id': 'UUA1d3HFGFUmkKr2JIUA5Vlw'}

In [9]:
def iter_playlist_items(playlist_id: str):
    page_token = None
    
    while True:
        data = yt_get(
            "playlistItems",
            {
                "part": "snippet,contentDetails",
                "playlistId": playlist_id,
                "maxResults": 50,
                "pageToken": page_token,
            },
        )
        
        for item in data.get("items", []):
            yield item
        
        page_token = data.get("nextPageToken")
        if not page_token:
            break

In [10]:
def parse_video_row(item: dict) -> dict:
    sn = item["snippet"]
    video_id = sn["resourceId"]["videoId"]
    published_at = pd.Timestamp(sn["publishedAt"])
    title = sn.get("title", "")
    description = sn.get("description", "")
    
    return {
        "video_id": video_id,
        "youtube_url": f"https://www.youtube.com/watch?v={video_id}",
        "title": title,
        "description": description,
        "published_at": published_at,
        "channel_title": sn.get("videoOwnerChannelTitle"),
    }

rows = [parse_video_row(x) for x in iter_playlist_items(channel_info["uploads_playlist_id"])]
df = pd.DataFrame(rows)

df.shape
df.head(3)

,video_id,youtube_url,title,description,published_at,channel_title
0,NqHPD88j7ps,https://www.youtube.com/watch?v=NqHPD88j7ps,Something couldn’t believe what was happening ...,,2026-03-25 20:06:50+00:00,VALORANT Champions Tour
1,D5FnNFL-coE,https://www.youtube.com/watch?v=D5FnNFL-coE,The crosshairs of the #VALORANTMasters Santiag...,Download VALORANT now: https://playvalorant.co...,2026-03-25 17:01:40+00:00,VALORANT Champions Tour
2,ekLPNLKE-PI,https://www.youtube.com/watch?v=ekLPNLKE-PI,A difficult moment handled with class #valoran...,Download VALORANT now: https://playvalorant.co...,2026-03-20 19:59:15+00:00,VALORANT Champions Tour

In [11]:
mask_date = (df["published_at"] >= DATE_FROM) & (df["published_at"] < DATE_TO)

mask_event = (
    df["title"].str.contains("Masters Santiago", case=False, na=False)
    | df["description"].str.contains("Masters Santiago", case=False, na=False)
)

cand = df.loc[mask_date & mask_event].copy()
cand = cand.sort_values("published_at").reset_index(drop=True)

cand[["published_at", "title", "youtube_url"]].head(20)
print("candidate videos:", len(cand))

candidate videos: 99

In [12]:

def parse_match_title(title: str) -> dict:
    """
    例:
    'T1 vs. G2 - VALORANT Masters Santiago - Playoffs'
    'Sentinels vs. Gen.G - VALORANT Masters Santiago - SWISS'
    """

    t = title.strip()

    # 区切りを " - " で分割
    parts = [p.strip() for p in t.split(" - ")]

    # デフォルト値
    team_a = None
    team_b = None
    event = None
    stage = None

    # 少なくとも
    # [0] = "teamA vs. teamB"
    # [1] = "VALORANT Masters Santiago"
    # [2] = "Playoffs" など
    if len(parts) >= 3:
        match_part = parts[0]
        event = parts[1]
        stage = " - ".join(parts[2:])   # 念のため後ろ全部つなぐ

        # "vs." / "vs" / "VS." あたりを許容
        m_vs = re.match(r"^(.*?)\s+vs\.?\s+(.*?)$", match_part, flags=re.I)
        if m_vs:
            team_a = m_vs.group(1).strip()
            team_b = m_vs.group(2).strip()

    return {
        "team_a": team_a,
        "team_b": team_b,
        "event": event,
        "stage": stage,
        "map_no": None,   # 今回は map ごとの情報がない
    }


parsed = cand["title"].apply(parse_match_title).apply(pd.Series)

out = pd.concat([cand, parsed], axis=1)

out = out[
    [
        "published_at",
        "event",
        "stage",
        "team_a",
        "team_b",
        "map_no",
        "video_id",
        "youtube_url",
        "title",
    ]
].sort_values(["published_at", "stage", "team_a", "team_b"])

out.head(30)

,published_at,event,stage,team_a,team_b,map_no,video_id,youtube_url,title
0,2026-02-28 14:56:29+00:00,NaN,NaN,NaN,NaN,NaN,MG9Qcq3jFQg,https://www.youtube.com/watch?v=MG9Qcq3jFQg,The Hunt Begins | VALORANT Masters Santiago Op...
1,2026-02-28 19:29:02+00:00,VALORANT Masters Santiago,SWISS,M8,EDG,NaN,72YPJbZQMdU,https://www.youtube.com/watch?v=72YPJbZQMdU,M8 vs. EDG - VALORANT Masters Santiago - SWISS
2,2026-02-28 19:42:28+00:00,NaN,NaN,NaN,NaN,NaN,ymtkWiyYB7M,https://www.youtube.com/watch?v=ymtkWiyYB7M,M8 vs. EDG | MATCH HIGHLIGHTS | VALORANT Maste...
3,2026-02-28 21:40:12+00:00,VALORANT Masters Santiago,SWISS,XLG,NRG,NaN,ISayDnJokzk,https://www.youtube.com/watch?v=ISayDnJokzk,XLG vs. NRG - VALORANT Masters Santiago - SWISS
4,2026-02-28 21:41:42+00:00,NaN,NaN,NaN,NaN,NaN,ORFPUIzF7TI,https://www.youtube.com/watch?v=ORFPUIzF7TI,Vertical | M8 vs. EDG | XLG vs. NRG — VALORANT...
5,2026-02-28 21:51:32+00:00,NaN,NaN,NaN,NaN,NaN,Y-NTCxXjQmE,https://www.youtube.com/watch?v=Y-NTCxXjQmE,M8 vs. EDG | XLG vs. NRG — VALORANT Masters Sa...
6,2026-02-28 22:04:52+00:00,NaN,NaN,NaN,NaN,NaN,MXo1N9szsbY,https://www.youtube.com/watch?v=MXo1N9szsbY,XLG vs. NRG | MATCH HIGHLIGHTS | VALORANT Mast...
7,2026-02-28 23:00:33+00:00,NaN,NaN,NaN,NaN,NaN,-uqHX2ni05I,https://www.youtube.com/watch?v=-uqHX2ni05I,The crowds at #VALORANTMasters Santiago brough...
8,2026-03-01 17:10:07+00:00,NaN,NaN,NaN,NaN,NaN,aNtmM72aRFM,https://www.youtube.com/watch?v=aNtmM72aRFM,M8 vs. EDG – VALORANT Masters Santiago – Match...
9,2026-03-01 17:11:33+00:00,NaN,NaN,NaN,NaN,NaN,reCEUviL_WI,https://www.youtube.com/watch?v=reCEUviL_WI,XLG vs. NRG – VALORANT Masters Santiago – Matc...
10,2026-03-01 18:58:19+00:00,VALORANT Masters Santiago,SWISS,G2,PRX,NaN,KKa_YM-8MHk,https://www.youtube.com/watch?v=KKa_YM-8MHk,G2 vs. PRX - VALORANT Masters Santiago - SWISS
11,2026-03-01 19:24:10+00:00,NaN,NaN,NaN,NaN,NaN,sNX2xA44m3s,https://www.youtube.com/watch?v=sNX2xA44m3s,G2 vs. PRX | MATCH HIGHLIGHTS | VALORANT Maste...
12,2026-03-01 19:33:19+00:00,NaN,NaN,NaN,NaN,NaN,e6dRDi0eZjA,https://www.youtube.com/watch?v=e6dRDi0eZjA,Stax gets the first ACE of #VALORANTMasters Sa...
13,2026-03-01 19:34:05+00:00,NaN,NaN,NaN,NaN,NaN,zvA0mn7pNAM,https://www.youtube.com/watch?v=zvA0mn7pNAM,G2 vs. PRX – VALORANT Masters Santiago – Match...
14,2026-03-01 21:22:50+00:00,VALORANT Masters Santiago,SWISS,T1,TL,NaN,qnO-LlwW2tM,https://www.youtube.com/watch?v=qnO-LlwW2tM,T1 vs. TL - VALORANT Masters Santiago - SWISS
15,2026-03-01 21:39:45+00:00,NaN,NaN,NaN,NaN,NaN,WLz5lTdTsCo,https://www.youtube.com/watch?v=WLz5lTdTsCo,Vertical | G2 vs. PRX | T1 vs. TL — VALORANT M...
16,2026-03-01 21:44:23+00:00,NaN,NaN,NaN,NaN,NaN,nX1Cu0jClG4,https://www.youtube.com/watch?v=nX1Cu0jClG4,G2 vs. PRX | T1 vs. TL — VALORANT Masters Sant...
17,2026-03-01 21:46:45+00:00,NaN,NaN,NaN,NaN,NaN,7CfpMnHt3HM,https://www.youtube.com/watch?v=7CfpMnHt3HM,T1 vs. TL | MATCH HIGHLIGHTS | VALORANT Master...
18,2026-03-01 21:51:57+00:00,NaN,NaN,NaN,NaN,NaN,xepEtXFRJ20,https://www.youtube.com/watch?v=xepEtXFRJ20,T1 vs. TL – VALORANT Masters Santiago – Match ...
19,2026-03-02 19:00:33+00:00,NaN,NaN,NaN,NaN,NaN,lJpUSu6_Q84,https://www.youtube.com/watch?v=lJpUSu6_Q84,The #VALORANTMasters Santiago crowd came throu...
20,2026-03-02 21:34:50+00:00,VALORANT Masters Santiago,SWISS,PRX,NRG,NaN,MXvyAVsnqTc,https://www.youtube.com/watch?v=MXvyAVsnqTc,PRX vs. NRG - VALORANT Masters Santiago - SWISS
21,2026-03-02 21:50:55+00:00,NaN,NaN,NaN,NaN,NaN,SfSn6C8xtkU,https://www.youtube.com/watch?v=SfSn6C8xtkU,PRX vs. NRG | MATCH HIGHLIGHTS | VALORANT Mast...
22,2026-03-02 23:19:33+00:00,VALORANT Masters Santiago,SWISS,M8,TL,NaN,RTmdmtwXklY,https://www.youtube.com/watch?v=RTmdmtwXklY,M8 vs. TL - VALORANT Masters Santiago - SWISS
23,2026-03-02 23:35:00+00:00,NaN,NaN,NaN,NaN,NaN,6E3NfY07Ndo,https://www.youtube.com/watch?v=6E3NfY07Ndo,Vertical | PRX vs. NRG | TL vs. M8 — VALORANT ...
24,2026-03-02 23:38:48+00:00,NaN,NaN,NaN,NaN,NaN,tPfTv0Bp-Hg,https://www.youtube.com/watch?v=tPfTv0Bp-Hg,PRX vs. NRG | TL vs. M8 — VALORANT Masters San...
25,2026-03-02 23:40:07+00:00,NaN,NaN,NaN,NaN,NaN,Ze0t1V50JaE,https://www.youtube.com/watch?v=Ze0t1V50JaE,M8 vs. TL | MATCH HIGHLIGHTS | VALORANT Master...
26,2026-03-03 00:10:24+00:00,NaN,NaN,NaN,NaN,NaN,wr5ZO0PzYn4,https://www.youtube.com/watch?v=wr5ZO0PzYn4,M8 vs TL | MATCH HIGHLIGHTS | VALORANT Masters...
27,2026-03-03 19:51:00+00:00,VALORANT Masters Santiago,SWISS,EDG,T1,NaN,-hr5Fl56DEA,https://www.youtube.com/watch?v=-hr5Fl56DEA,EDG vs. T1 - VALORANT Masters Santiago - SWISS
28,2026-03-03 20:20:56+00:00,NaN,NaN,NaN,NaN,NaN,y82r_taW0FU,https://www.youtube.com/watch?v=y82r_taW0FU,EDG vs. T1 | MATCH HIGHLIGHTS | VALORANT Maste...
29,2026-03-03 21:04:41+00:00,NaN,NaN,NaN,NaN,NaN,O8rgyXen-8U,https://www.youtube.com/watch?v=O8rgyXen-8U,EDG vs T1 | MATCH HIGHLIGHTS | VALORANT Master...

In [13]:
required_cols = ["event", "stage", "team_a", "team_b"]

vod_df = out.dropna(subset=required_cols).copy().reset_index(drop=True)
vod_df

,published_at,event,stage,team_a,team_b,map_no,video_id,youtube_url,title
0,2026-02-28 19:29:02+00:00,VALORANT Masters Santiago,SWISS,M8,EDG,NaN,72YPJbZQMdU,https://www.youtube.com/watch?v=72YPJbZQMdU,M8 vs. EDG - VALORANT Masters Santiago - SWISS
1,2026-02-28 21:40:12+00:00,VALORANT Masters Santiago,SWISS,XLG,NRG,NaN,ISayDnJokzk,https://www.youtube.com/watch?v=ISayDnJokzk,XLG vs. NRG - VALORANT Masters Santiago - SWISS
2,2026-03-01 18:58:19+00:00,VALORANT Masters Santiago,SWISS,G2,PRX,NaN,KKa_YM-8MHk,https://www.youtube.com/watch?v=KKa_YM-8MHk,G2 vs. PRX - VALORANT Masters Santiago - SWISS
3,2026-03-01 21:22:50+00:00,VALORANT Masters Santiago,SWISS,T1,TL,NaN,qnO-LlwW2tM,https://www.youtube.com/watch?v=qnO-LlwW2tM,T1 vs. TL - VALORANT Masters Santiago - SWISS
4,2026-03-02 21:34:50+00:00,VALORANT Masters Santiago,SWISS,PRX,NRG,NaN,MXvyAVsnqTc,https://www.youtube.com/watch?v=MXvyAVsnqTc,PRX vs. NRG - VALORANT Masters Santiago - SWISS
5,2026-03-02 23:19:33+00:00,VALORANT Masters Santiago,SWISS,M8,TL,NaN,RTmdmtwXklY,https://www.youtube.com/watch?v=RTmdmtwXklY,M8 vs. TL - VALORANT Masters Santiago - SWISS
6,2026-03-03 19:51:00+00:00,VALORANT Masters Santiago,SWISS,EDG,T1,NaN,-hr5Fl56DEA,https://www.youtube.com/watch?v=-hr5Fl56DEA,EDG vs. T1 - VALORANT Masters Santiago - SWISS
7,2026-03-03 21:48:38+00:00,VALORANT Masters Santiago,SWISS,XLG,G2,NaN,t2q1UkGg-jg,https://www.youtube.com/watch?v=t2q1UkGg-jg,XLG vs. G2 - VALORANT Masters Santiago - SWISS
8,2026-03-04 20:20:55+00:00,VALORANT Masters Santiago,SWISS,NRG,TL,NaN,gcbgzFL92XU,https://www.youtube.com/watch?v=gcbgzFL92XU,NRG vs. TL - VALORANT Masters Santiago - SWISS
9,2026-03-04 22:45:41+00:00,VALORANT Masters Santiago,SWISS,G2,T1,NaN,dX0hUGXoJyk,https://www.youtube.com/watch?v=dX0hUGXoJyk,G2 vs. T1 - VALORANT Masters Santiago - SWISS
10,2026-03-06 20:57:50+00:00,VALORANT Masters Santiago,Playoffs,FUR,PRX,NaN,CSk1dca-rss,https://www.youtube.com/watch?v=CSk1dca-rss,FUR vs. PRX - VALORANT Masters Santiago - Play...
11,2026-03-06 22:56:34+00:00,VALORANT Masters Santiago,Playoffs,NS,M8,NaN,-wX7dk_wdRU,https://www.youtube.com/watch?v=-wX7dk_wdRU,NS vs. M8 - VALORANT Masters Santiago - Playoffs
12,2026-03-07 20:39:05+00:00,VALORANT Masters Santiago,Playoffs,BBL,NRG,NaN,ufgHES26TeE,https://www.youtube.com/watch?v=ufgHES26TeE,BBL vs. NRG - VALORANT Masters Santiago - Play...
13,2026-03-07 22:28:51+00:00,VALORANT Masters Santiago,Playoffs,AG,G2,NaN,Hl65QMr-f8w,https://www.youtube.com/watch?v=Hl65QMr-f8w,AG vs. G2 - VALORANT Masters Santiago - Playoffs
14,2026-03-08 20:32:40+00:00,VALORANT Masters Santiago,Playoffs,BBL,FUR,NaN,timJ-FSwaAM,https://www.youtube.com/watch?v=timJ-FSwaAM,BBL vs. FUR - VALORANT Masters Santiago - Play...
15,2026-03-08 23:37:33+00:00,VALORANT Masters Santiago,Playoffs,M8,AG,NaN,3cyBswcpKBg,https://www.youtube.com/watch?v=3cyBswcpKBg,M8 vs. AG - VALORANT Masters Santiago - Playoffs
16,2026-03-09 21:17:50+00:00,VALORANT Masters Santiago,Playoffs,NS,G2,NaN,EpC_Wn5viOQ,https://www.youtube.com/watch?v=EpC_Wn5viOQ,NS vs. G2 - VALORANT Masters Santiago - Playoffs
17,2026-03-09 23:48:10+00:00,VALORANT Masters Santiago,Playoffs,PRX,NRG,NaN,lbH8PxtdlHs,https://www.youtube.com/watch?v=lbH8PxtdlHs,PRX vs. NRG - VALORANT Masters Santiago - Play...
18,2026-03-10 20:13:16+00:00,VALORANT Masters Santiago,Playoffs,G2,BBL,NaN,nFCE8az8CTw,https://www.youtube.com/watch?v=nFCE8az8CTw,G2 vs. BBL - VALORANT Masters Santiago - Playoffs
19,2026-03-10 23:13:12+00:00,VALORANT Masters Santiago,Playoffs,PRX,AG,NaN,6OBZIQwBmM8,https://www.youtube.com/watch?v=6OBZIQwBmM8,PRX vs. AG - VALORANT Masters Santiago - Playoffs
20,2026-03-13 19:41:32+00:00,VALORANT Masters Santiago,Playoffs,NS,NRG,NaN,zSks_VrlpCE,https://www.youtube.com/watch?v=zSks_VrlpCE,NS vs. NRG - VALORANT Masters Santiago - Playoffs
21,2026-03-13 22:27:20+00:00,VALORANT Masters Santiago,Playoffs,PRX,G2,NaN,Q5-jDQhlYTE,https://www.youtube.com/watch?v=Q5-jDQhlYTE,PRX vs. G2 - VALORANT Masters Santiago - Playoffs
22,2026-03-14 21:30:43+00:00,VALORANT Masters Santiago,Lower Finals,NRG,PRX,NaN,khErde2Dhbg,https://www.youtube.com/watch?v=khErde2Dhbg,NRG vs. PRX - VALORANT Masters Santiago - Lowe...
23,2026-03-15 20:58:41+00:00,VALORANT Masters Santiago,Grand Final,NS,PRX,NaN,NR1AEXusjac,https://www.youtube.com/watch?v=NR1AEXusjac,NS vs. PRX - VALORANT Masters Santiago - Grand...

In [14]:
from pathlib import Path

Path("../data/raw").mkdir(parents=True, exist_ok=True)
Path("../data/interim").mkdir(parents=True, exist_ok=True)
Path("../data/processed").mkdir(parents=True, exist_ok=True)

vod_df.to_csv("../data/raw/masters_santiago_2026_vods.csv", index=False, encoding="utf-8-sig")
print("saved:", len(vod_df), "rows")

saved: 24 rows